site_name: SCION Tutorials
site_description: A collection of tutorial pages for SCION

site_dir: docs
docs_dir: content

theme:
    name: null
    custom_dir: 'mkdocs-material/material'

    include_search_page: false
    search_index_only: true

    language: en
    feature:
      tabs: false
    palette:
      primary:
      accent:
    font:
      text: Roboto
      code: Roboto Mono
    favicon: assets/images/favicon.ico
    logo:
      icon: "\uE80C"

markdown_extensions:
    - admonition
    - codehilite
    - meta
    - toc:
        permalink: true


copyright: 'Copyright &copy 2017, Network Security Group, ETH Zurich'

# Options
extra:
  search:
    languages: 'en'

  social:
    - type: globe
      link: https://www.scion-architecture.net/
    - type: github-alt
      link: https://github.com/netsec-ethz/

pages:
    - Home: index.md
    - How to setup on different platforms:
      - Ubuntu 16.04 x86-64: native_setup/ubuntu_x86_build.md
      - Raspberry PI &ndash; Ubuntu: native_setup/rpi_ubuntu.md
      - Virtual machine via VPN: virtual_machine_setup/dynamic_ip.md
      - Virtual machine with static public IP: virtual_machine_setup/static_ip.md
      - Verifying the installation: general_scion_configuration/verifying_scion_installation.md
    - How to connect:
      - Running SCION on a local topology: general_scion_configuration/local_top.md
      - Set up an AS and connect to the SCION network: general_scion_configuration/public_ip.md
      - Connect to the SCION network via VPN: general_scion_configuration/vpn_setup.md
      - Set up an endhost and connect to a local AS: general_scion_configuration/vpn_setup.md

    - How to use:
      - Visualization tool (SCION-viz): general_scion_configuration/scion_viz.md
      - Read a temperature sensor over the SCION network: sample_projects/fetch_temperature.md
      - Access a video camera over the SCION network: sample_projects/access_camera.md
      - Using multipath in SCION: sample_projects/multipath.md
      - Configuring path selection: general_scion_configuration/influence_path_selection.md
      - Configuring the SCION IP gateway: general_scion_configuration/setup_sig.md
    - AS Visualization:
      - Running AS Visualizations: as_visualization/running_asviz.md
      - Browser AS Visualization: as_visualization/browser_asviz.md
      - Command-line AS Visualization: as_visualization/command_asviz.md